name: cloudflare pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Change if you need git info

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      
      - name: Print File Content
        run: ls ./assets/Fonts
          
      - name: Build
        run: zig build --summary new
          
      - name: Deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: personal-blog
          directory: ./zig-out